<a href="https://colab.research.google.com/github/Anna-Tereshchuk/Data-Engineering-Notebooks/blob/main/data_cleaning_and_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DataFrame**  у pandas - це двовимірна структура даних, схожа на двовимірний масив або таблицю з рядками та стовпцями.

In [23]:
import pandas as pd

df = pd.read_csv('/Bike Sharing.csv', encoding='latin1')
print(df)

      ID        Date  Season  Year  Month  Holiday  Weekday  Working Day  \
0      1  01-01-2011       1     0      1        0        6            0
1      2  02-01-2011       1     0      1        0        0            0
2      3  03-01-2011       1     0      1        0        1            1
3      4  04-01-2011       1     0      1        0        2            1
4      5  05-01-2011       1     0      1        0        3            1
..   ...         ...     ...   ...    ...      ...      ...          ...
726  727  27-12-2012       1     1     12        0        4            1
727  728  28-12-2012       1     1     12        0        5            1
728  729  29-12-2012       1     1     12        0        6            0
729  730  30-12-2012       1     1     12        0        0            0
730  731  31-12-2012       1     1     12        0        1            1

     Weather      Temp     Temp©  Humidity  Windspeed  Casual Rider  \
0          2  0.344167  0.363625  0.805833   0.160446           331
1          2  0.363478  0.353739  0.696087   0.248539           131
2          1  0.196364  0.189405  0.437273   0.248309           120
3          1  0.200000  0.212122  0.590435   0.160296           108
4          1  0.226957  0.229270  0.436957   0.186900            82
..       ...       ...       ...       ...        ...           ...
726        2  0.254167  0.226642  0.652917   0.350133           247
727        2  0.253333  0.255046  0.590000   0.155471           644
728        2  0.253333  0.242400  0.752917   0.124383           159
729        1  0.255833  0.231700  0.483333   0.350754           364
730        2  0.215833  0.223487  0.577500   0.154846           439

     Registered Rider  Total Rider
0                 654          985
1                 670          801
2                1229         1349
3                1454         1562
4                1518         1600
..                ...          ...
726              1867         2114
727              2451         3095
728              1182         1341
729              1432         1796
730              2290         2729

[731 rows x 16 columns]

In [41]:
print(df.head(20).to_string())

    ID        Date  Season  Year  Month  Holiday  Weekday  Working Day  Weather      Temp     Temp©  Humidity  Windspeed  Casual Rider  Registered Rider  Total Rider
0    1  01-01-2011       1   NaN      1      NaN      6.0        777.0        2  0.344167  0.363625  0.805833   0.160446           331               654          985
1    2  02-01-2011       1   NaN      1      NaN      NaN        777.0        2  0.363478  0.353739  0.696087   0.248539           131               670          801
2    3  03-01-2011       1   NaN      1      NaN      1.0          1.0        1  0.196364  0.189405  0.437273   0.248309           120              1229         1349
3    4  04-01-2011       1   NaN      1      NaN      2.0          1.0        1  0.200000  0.212122  0.590435   0.160296           108              1454         1562
4    5  05-01-2011       1   NaN      1      NaN      3.0          1.0        1  0.226957  0.229270  0.436957   0.186900            82              1518         1600
5    6  06-01-2011       1   NaN      1      NaN      4.0          1.0        1  0.204348  0.233209  0.518261   0.089565            88              1518         1606
6    7  07-01-2011       1   NaN      1      NaN      5.0          1.0        2  0.196522  0.208839  0.498696   0.168726           148              1362         1510
7    8  08-01-2011       1   NaN      1      NaN      6.0        777.0        2  0.165000  0.162254  0.535833   0.266804            68               891          959
8    9  09-01-2011       1   NaN      1      NaN      NaN        777.0        1  0.138333  0.116175  0.434167   0.361950            54               768          822
9   10  10-01-2011       1   NaN      1      NaN      1.0          1.0        1  0.150833  0.150888  0.482917   0.223267            41              1280         1321
10  11  11-01-2011       1   NaN      1      NaN      2.0          1.0        2  0.169091  0.191464  0.686364   0.122132            43              1220         1263
11  12  12-01-2011       1   NaN      1      NaN      3.0          1.0        1  0.172727  0.160473  0.599545   0.304627            25              1137         1162
12  13  13-01-2011       1   NaN      1      NaN      4.0          1.0        1  0.165000  0.150883  0.470417   0.301000            38              1368         1406
13  14  14-01-2011       1   NaN      1      NaN      5.0          1.0        1  0.160870  0.188413  0.537826   0.126548            54              1367         1421
14  15  15-01-2011       1   NaN      1      NaN      6.0        777.0        2  0.233333  0.248112  0.498750   0.157963           222              1026         1248
15  16  16-01-2011       1   NaN      1      NaN      NaN        777.0        1  0.231667  0.234217  0.483750   0.188433           251               953         1204
16  17  17-01-2011       1   NaN      1      1.0      1.0        777.0        2  0.175833  0.176771  0.537500   0.194017           117               883         1000
17  18  18-01-2011       1   NaN      1      NaN      2.0          1.0        2  0.216667  0.232333  0.861667   0.146775             9               674          683
18  19  19-01-2011       1   NaN      1      NaN      3.0          1.0        2  0.292174  0.298422  0.741739   0.208317            78              1572         1650
19  20  20-01-2011       1   NaN      1      NaN      4.0          1.0        2  0.261667  0.255050  0.538333   0.195904            83              1844         1927

**Видалення рядків з порожніми клітинками**

Функція` dropna`:
Використовуйте **функцію dropna**, щоб видалити всі рядки, які містять хоча б одну порожню клітинку.

In [35]:
new_df = df.dropna()
print(new_df.to_string())
print(new_df.head(20))

      ID        Date  Season  Year  Month  Holiday  Weekday  Working Day  Weather      Temp     Temp©  Humidity  Windspeed  Casual Rider  Registered Rider  Total Rider
366  367  02-01-2012       1   1.0      1      1.0      1.0        777.0        1  0.273043  0.252304  0.381304   0.329665           244              1707         1951
380  381  16-01-2012       1   1.0      1      1.0      1.0        777.0        1  0.190000  0.190663  0.522500   0.231358           217              2081         2298
415  416  20-02-2012       1   1.0      2      1.0      1.0        777.0        1  0.280000  0.273391  0.507826   0.229083           502              2627         3129
471  472  16-04-2012       2   1.0      4      1.0      1.0        777.0        1  0.664167  0.614925  0.561667   0.284829          1198              5172         6370
513  514  28-05-2012       2   1.0      5      1.0      1.0        777.0        1  0.712500  0.679300  0.676250   0.196521          2557              3486         6043
550  551  04-07-2012       3   1.0      7      1.0      3.0        777.0        1  0.789167  0.732337  0.538750   0.134950          2562              4841         7403
611  612  03-09-2012       3   1.0      9      1.0      1.0        777.0        1  0.707500  0.661629  0.790833   0.151121          1965              4069         6034
646  647  08-10-2012       4   1.0     10      1.0      1.0        777.0        2  0.383333  0.387608  0.709583   0.189679           874              4604         5478
681  682  12-11-2012       4   1.0     11      1.0      1.0        777.0        1  0.485000  0.475383  0.741667   0.173517          1097              5172         6269
691  692  22-11-2012       4   1.0     11      1.0      4.0        777.0        1  0.340000  0.350371  0.580417   0.052871           955              1470         2425
724  725  25-12-2012       1   1.0     12      1.0      2.0        777.0        2  0.291304  0.294465  0.734783   0.168726           440               573         1013
      ID        Date  Season  Year  Month  Holiday  Weekday  Working Day  \
366  367  02-01-2012       1   1.0      1      1.0      1.0        777.0
380  381  16-01-2012       1   1.0      1      1.0      1.0        777.0
415  416  20-02-2012       1   1.0      2      1.0      1.0        777.0
471  472  16-04-2012       2   1.0      4      1.0      1.0        777.0
513  514  28-05-2012       2   1.0      5      1.0      1.0        777.0
550  551  04-07-2012       3   1.0      7      1.0      3.0        777.0
611  612  03-09-2012       3   1.0      9      1.0      1.0        777.0
646  647  08-10-2012       4   1.0     10      1.0      1.0        777.0
681  682  12-11-2012       4   1.0     11      1.0      1.0        777.0
691  692  22-11-2012       4   1.0     11      1.0      4.0        777.0
724  725  25-12-2012       1   1.0     12      1.0      2.0        777.0

     Weather      Temp     Temp©  Humidity  Windspeed  Casual Rider  \
366        1  0.273043  0.252304  0.381304   0.329665           244
380        1  0.190000  0.190663  0.522500   0.231358           217
415        1  0.280000  0.273391  0.507826   0.229083           502
471        1  0.664167  0.614925  0.561667   0.284829          1198
513        1  0.712500  0.679300  0.676250   0.196521          2557
550        1  0.789167  0.732337  0.538750   0.134950          2562
611        1  0.707500  0.661629  0.790833   0.151121          1965
646        2  0.383333  0.387608  0.709583   0.189679           874
681        1  0.485000  0.475383  0.741667   0.173517          1097
691        1  0.340000  0.350371  0.580417   0.052871           955
724        2  0.291304  0.294465  0.734783   0.168726           440

     Registered Rider  Total Rider
366              1707         1951
380              2081         2298
415              2627         3129
471              5172         6370
513              3486         6043
550              4841         7403
611              4069         6034
646              4604         5478
681              5172         6269
691              1470         2425
724               573         1013

для того щоб працювати з Null  значеннями ми спочатку їх створимо

In [36]:
import pandas as pd
import numpy as np

# Завантаження CSV файлу
df = pd.read_csv('/Bike Sharing.csv', encoding='latin1')

# Виведення оригінального DataFrame
print("Original DataFrame:")
print(df)

# Заміна значень 0 на NaN (null)
df.replace(0, np.nan, inplace=True)

# Виведення зміненого DataFrame
print("\nDataFrame after replacing 0 with NaN:")
print(df.head(20))

Original DataFrame:
      ID        Date  Season  Year  Month  Holiday  Weekday  Working Day  \
0      1  01-01-2011       1     0      1        0        6            0
1      2  02-01-2011       1     0      1        0        0            0
2      3  03-01-2011       1     0      1        0        1            1
3      4  04-01-2011       1     0      1        0        2            1
4      5  05-01-2011       1     0      1        0        3            1
..   ...         ...     ...   ...    ...      ...      ...          ...
726  727  27-12-2012       1     1     12        0        4            1
727  728  28-12-2012       1     1     12        0        5            1
728  729  29-12-2012       1     1     12        0        6            0
729  730  30-12-2012       1     1     12        0        0            0
730  731  31-12-2012       1     1     12        0        1            1

     Weather      Temp     Temp©  Humidity  Windspeed  Casual Rider  \
0          2  0.344167  0.363625  0.805833   0.160446           331
1          2  0.363478  0.353739  0.696087   0.248539           131
2          1  0.196364  0.189405  0.437273   0.248309           120
3          1  0.200000  0.212122  0.590435   0.160296           108
4          1  0.226957  0.229270  0.436957   0.186900            82
..       ...       ...       ...       ...        ...           ...
726        2  0.254167  0.226642  0.652917   0.350133           247
727        2  0.253333  0.255046  0.590000   0.155471           644
728        2  0.253333  0.242400  0.752917   0.124383           159
729        1  0.255833  0.231700  0.483333   0.350754           364
730        2  0.215833  0.223487  0.577500   0.154846           439

     Registered Rider  Total Rider
0                 654          985
1                 670          801
2                1229         1349
3                1454         1562
4                1518         1600
..                ...          ...
726              1867         2114
727              2451         3095
728              1182         1341
729              1432         1796
730              2290         2729

[731 rows x 16 columns]

DataFrame after replacing 0 with NaN:
    ID        Date  Season  Year  Month  Holiday  Weekday  Working Day  \
0    1  01-01-2011       1   NaN      1      NaN      6.0          NaN
1    2  02-01-2011       1   NaN      1      NaN      NaN          NaN
2    3  03-01-2011       1   NaN      1      NaN      1.0          1.0
3    4  04-01-2011       1   NaN      1      NaN      2.0          1.0
4    5  05-01-2011       1   NaN      1      NaN      3.0          1.0
5    6  06-01-2011       1   NaN      1      NaN      4.0          1.0
6    7  07-01-2011       1   NaN      1      NaN      5.0          1.0
7    8  08-01-2011       1   NaN      1      NaN      6.0          NaN
8    9  09-01-2011       1   NaN      1      NaN      NaN          NaN
9   10  10-01-2011       1   NaN      1      NaN      1.0          1.0
10  11  11-01-2011       1   NaN      1      NaN      2.0          1.0
11  12  12-01-2011       1   NaN      1      NaN      3.0          1.0
12  13  13-01-2011       1   NaN      1      NaN      4.0          1.0
13  14  14-01-2011       1   NaN      1      NaN      5.0          1.0
14  15  15-01-2011       1   NaN      1      NaN      6.0          NaN
15  16  16-01-2011       1   NaN      1      NaN      NaN          NaN
16  17  17-01-2011       1   NaN      1      1.0      1.0          NaN
17  18  18-01-2011       1   NaN      1      NaN      2.0          1.0
18  19  19-01-2011       1   NaN      1      NaN      3.0          1.0
19  20  20-01-2011       1   NaN      1      NaN      4.0          1.0

    Weather      Temp     Temp©  Humidity  Windspeed  Casual Rider  \
0         2  0.344167  0.363625  0.805833   0.160446           331
1         2  0.363478  0.353739  0.696087   0.248539           131
2         1  0.196364  0.189405  0.437273   0.248309           120
3         1  0.200000  0.212122  0.590435   0.160296           108
4         1  0.226957  0.229270  0.436957   0.186900            82
5         1  0.204348  0.233209  0.518261   0.089565            88
6         2  0.196522  0.208839  0.498696   0.168726           148
7         2  0.165000  0.162254  0.535833   0.266804            68
8         1  0.138333  0.116175  0.434167   0.361950            54
9         1  0.150833  0.150888  0.482917   0.223267            41
10        2  0.169091  0.191464  0.686364   0.122132            43
11        1  0.172727  0.160473  0.599545   0.304627            25
12        1  0.165000  0.150883  0.470417   0.301000            38
13        1  0.160870  0.188413  0.537826   0.126548            54
14        2  0.233333  0.248112  0.498750   0.157963           222
15        1  0.231667  0.234217  0.483750   0.188433           251
16        2  0.175833  0.176771  0.537500   0.194017           117
17        2  0.216667  0.232333  0.861667   0.146775             9
18        2  0.292174  0.298422  0.741739   0.208317            78
19        2  0.261667  0.255050  0.538333   0.195904            83

    Registered Rider  Total Rider
0                654          985
1                670          801
2               1229         1349
3               1454         1562
4               1518         1600
5               1518         1606
6               1362         1510
7                891          959
8                768          822
9               1280         1321
10              1220         1263
11              1137         1162
12              1368         1406
13              1367         1421
14              1026         1248
15               953         1204
16               883         1000
17               674          683
18              1572         1650
19              1844         1927

In [39]:
new_df = df.dropna()
print(new_df.head(20).to_string())

    ID        Date  Season   Year  Month  Holiday  Weekday  Working Day  Weather      Temp     Temp©  Humidity  Windspeed  Casual Rider  Registered Rider  Total Rider
0    1  01-01-2011       1  100.0      1    100.0      6.0        100.0        2  0.344167  0.363625  0.805833   0.160446           331               654          985
1    2  02-01-2011       1  100.0      1    100.0    100.0        100.0        2  0.363478  0.353739  0.696087   0.248539           131               670          801
2    3  03-01-2011       1  100.0      1    100.0      1.0          1.0        1  0.196364  0.189405  0.437273   0.248309           120              1229         1349
3    4  04-01-2011       1  100.0      1    100.0      2.0          1.0        1  0.200000  0.212122  0.590435   0.160296           108              1454         1562
4    5  05-01-2011       1  100.0      1    100.0      3.0          1.0        1  0.226957  0.229270  0.436957   0.186900            82              1518         1600
5    6  06-01-2011       1  100.0      1    100.0      4.0          1.0        1  0.204348  0.233209  0.518261   0.089565            88              1518         1606
6    7  07-01-2011       1  100.0      1    100.0      5.0          1.0        2  0.196522  0.208839  0.498696   0.168726           148              1362         1510
7    8  08-01-2011       1  100.0      1    100.0      6.0        100.0        2  0.165000  0.162254  0.535833   0.266804            68               891          959
8    9  09-01-2011       1  100.0      1    100.0    100.0        100.0        1  0.138333  0.116175  0.434167   0.361950            54               768          822
9   10  10-01-2011       1  100.0      1    100.0      1.0          1.0        1  0.150833  0.150888  0.482917   0.223267            41              1280         1321
10  11  11-01-2011       1  100.0      1    100.0      2.0          1.0        2  0.169091  0.191464  0.686364   0.122132            43              1220         1263
11  12  12-01-2011       1  100.0      1    100.0      3.0          1.0        1  0.172727  0.160473  0.599545   0.304627            25              1137         1162
12  13  13-01-2011       1  100.0      1    100.0      4.0          1.0        1  0.165000  0.150883  0.470417   0.301000            38              1368         1406
13  14  14-01-2011       1  100.0      1    100.0      5.0          1.0        1  0.160870  0.188413  0.537826   0.126548            54              1367         1421
14  15  15-01-2011       1  100.0      1    100.0      6.0        100.0        2  0.233333  0.248112  0.498750   0.157963           222              1026         1248
15  16  16-01-2011       1  100.0      1    100.0    100.0        100.0        1  0.231667  0.234217  0.483750   0.188433           251               953         1204
16  17  17-01-2011       1  100.0      1      1.0      1.0        100.0        2  0.175833  0.176771  0.537500   0.194017           117               883         1000
17  18  18-01-2011       1  100.0      1    100.0      2.0          1.0        2  0.216667  0.232333  0.861667   0.146775             9               674          683
18  19  19-01-2011       1  100.0      1    100.0      3.0          1.0        2  0.292174  0.298422  0.741739   0.208317            78              1572         1650
19  20  20-01-2011       1  100.0      1    100.0      4.0          1.0        2  0.261667  0.255050  0.538333   0.195904            83              1844         1927

In [38]:
df.fillna(100, inplace=True)
print(df.head(20).to_string())

    ID        Date  Season   Year  Month  Holiday  Weekday  Working Day  Weather      Temp     Temp©  Humidity  Windspeed  Casual Rider  Registered Rider  Total Rider
0    1  01-01-2011       1  100.0      1    100.0      6.0        100.0        2  0.344167  0.363625  0.805833   0.160446           331               654          985
1    2  02-01-2011       1  100.0      1    100.0    100.0        100.0        2  0.363478  0.353739  0.696087   0.248539           131               670          801
2    3  03-01-2011       1  100.0      1    100.0      1.0          1.0        1  0.196364  0.189405  0.437273   0.248309           120              1229         1349
3    4  04-01-2011       1  100.0      1    100.0      2.0          1.0        1  0.200000  0.212122  0.590435   0.160296           108              1454         1562
4    5  05-01-2011       1  100.0      1    100.0      3.0          1.0        1  0.226957  0.229270  0.436957   0.186900            82              1518         1600
5    6  06-01-2011       1  100.0      1    100.0      4.0          1.0        1  0.204348  0.233209  0.518261   0.089565            88              1518         1606
6    7  07-01-2011       1  100.0      1    100.0      5.0          1.0        2  0.196522  0.208839  0.498696   0.168726           148              1362         1510
7    8  08-01-2011       1  100.0      1    100.0      6.0        100.0        2  0.165000  0.162254  0.535833   0.266804            68               891          959
8    9  09-01-2011       1  100.0      1    100.0    100.0        100.0        1  0.138333  0.116175  0.434167   0.361950            54               768          822
9   10  10-01-2011       1  100.0      1    100.0      1.0          1.0        1  0.150833  0.150888  0.482917   0.223267            41              1280         1321
10  11  11-01-2011       1  100.0      1    100.0      2.0          1.0        2  0.169091  0.191464  0.686364   0.122132            43              1220         1263
11  12  12-01-2011       1  100.0      1    100.0      3.0          1.0        1  0.172727  0.160473  0.599545   0.304627            25              1137         1162
12  13  13-01-2011       1  100.0      1    100.0      4.0          1.0        1  0.165000  0.150883  0.470417   0.301000            38              1368         1406
13  14  14-01-2011       1  100.0      1    100.0      5.0          1.0        1  0.160870  0.188413  0.537826   0.126548            54              1367         1421
14  15  15-01-2011       1  100.0      1    100.0      6.0        100.0        2  0.233333  0.248112  0.498750   0.157963           222              1026         1248
15  16  16-01-2011       1  100.0      1    100.0    100.0        100.0        1  0.231667  0.234217  0.483750   0.188433           251               953         1204
16  17  17-01-2011       1  100.0      1      1.0      1.0        100.0        2  0.175833  0.176771  0.537500   0.194017           117               883         1000
17  18  18-01-2011       1  100.0      1    100.0      2.0          1.0        2  0.216667  0.232333  0.861667   0.146775             9               674          683
18  19  19-01-2011       1  100.0      1    100.0      3.0          1.0        2  0.292174  0.298422  0.741739   0.208317            78              1572         1650
19  20  20-01-2011       1  100.0      1    100.0      4.0          1.0        2  0.261667  0.255050  0.538333   0.195904            83              1844         1927

Заповнення null значень у конкретному стовпці:
але з деякими маніпуляціями щоб отримати Null значення

In [40]:
import pandas as pd
import numpy as np

# Завантаження CSV файлу
df = pd.read_csv('/Bike Sharing.csv', encoding='latin1')

# Заміна значень 0 на NaN (null)
df.replace(0, np.nan, inplace=True)

# Заповнення null значень у стовпці 'Working Day'
df['Working Day'] = df['Working Day'].fillna(777)

# Перевірка наявності null значень у стовпці 'Working Day' після fillna
print("\nNull values in 'Working Day' after fillna:")
print(df['Working Day'].isnull().sum())

# Виведення зміненого DataFrame
print("\nDataFrame after replacing null values in 'Working Day':")
print(df.head(20).to_string())

Null values in 'Working Day' after fillna:
0

DataFrame after replacing null values in 'Working Day':
    ID        Date  Season  Year  Month  Holiday  Weekday  Working Day  Weather      Temp     Temp©  Humidity  Windspeed  Casual Rider  Registered Rider  Total Rider
0    1  01-01-2011       1   NaN      1      NaN      6.0        777.0        2  0.344167  0.363625  0.805833   0.160446           331               654          985
1    2  02-01-2011       1   NaN      1      NaN      NaN        777.0        2  0.363478  0.353739  0.696087   0.248539           131               670          801
2    3  03-01-2011       1   NaN      1      NaN      1.0          1.0        1  0.196364  0.189405  0.437273   0.248309           120              1229         1349
3    4  04-01-2011       1   NaN      1      NaN      2.0          1.0        1  0.200000  0.212122  0.590435   0.160296           108              1454         1562
4    5  05-01-2011       1   NaN      1      NaN      3.0          1.0        1  0.226957  0.229270  0.436957   0.186900            82              1518         1600
5    6  06-01-2011       1   NaN      1      NaN      4.0          1.0        1  0.204348  0.233209  0.518261   0.089565            88              1518         1606
6    7  07-01-2011       1   NaN      1      NaN      5.0          1.0        2  0.196522  0.208839  0.498696   0.168726           148              1362         1510
7    8  08-01-2011       1   NaN      1      NaN      6.0        777.0        2  0.165000  0.162254  0.535833   0.266804            68               891          959
8    9  09-01-2011       1   NaN      1      NaN      NaN        777.0        1  0.138333  0.116175  0.434167   0.361950            54               768          822
9   10  10-01-2011       1   NaN      1      NaN      1.0          1.0        1  0.150833  0.150888  0.482917   0.223267            41              1280         1321
10  11  11-01-2011       1   NaN      1      NaN      2.0          1.0        2  0.169091  0.191464  0.686364   0.122132            43              1220         1263
11  12  12-01-2011       1   NaN      1      NaN      3.0          1.0        1  0.172727  0.160473  0.599545   0.304627            25              1137         1162
12  13  13-01-2011       1   NaN      1      NaN      4.0          1.0        1  0.165000  0.150883  0.470417   0.301000            38              1368         1406
13  14  14-01-2011       1   NaN      1      NaN      5.0          1.0        1  0.160870  0.188413  0.537826   0.126548            54              1367         1421
14  15  15-01-2011       1   NaN      1      NaN      6.0        777.0        2  0.233333  0.248112  0.498750   0.157963           222              1026         1248
15  16  16-01-2011       1   NaN      1      NaN      NaN        777.0        1  0.231667  0.234217  0.483750   0.188433           251               953         1204
16  17  17-01-2011       1   NaN      1      1.0      1.0        777.0        2  0.175833  0.176771  0.537500   0.194017           117               883         1000
17  18  18-01-2011       1   NaN      1      NaN      2.0          1.0        2  0.216667  0.232333  0.861667   0.146775             9               674          683
18  19  19-01-2011       1   NaN      1      NaN      3.0          1.0        2  0.292174  0.298422  0.741739   0.208317            78              1572         1650
19  20  20-01-2011       1   NaN      1      NaN      4.0          1.0        2  0.261667  0.255050  0.538333   0.195904            83              1844         1927